print("Olá turma do Python!")
print("Tudo joia!")
nome: str = input("Qual é o seu nome? ")
print(f"Olá, {nome}!")
print("Vamos começar!")
animal: str = input("Qual seu animal favorito? ")
print(f"Eu tambem adoro {animal}!")